<a href="https://colab.research.google.com/github/YoungjongPark87/python_programming/blob/master/python_11week.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])
a
a[0]
a[1]

np.int64(1)

In [10]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [11]:
a[:3]

array([10,  2,  3])

In [16]:
b = a[3:]
b
b[0] = 40
a


array([10,  2,  3, 40,  5,  6])

In [19]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a
a[1, 3] # 0부터 시작함에 따라서 2번째 행 4번째 열임

np.int64(8)

In [20]:
a.ndim

2

In [24]:
a.shape
len(a.shape) == a.ndim

True

In [26]:
a.size
import math
a.size == math.prod(a.shape)

True

In [27]:
a.dtype

dtype('int64')

In [28]:
np.zeros(2)

array([0., 0.])

In [29]:
np.ones(2)


array([1., 1.])

In [30]:
np.empty(2)

array([1., 1.])

In [31]:
np.arange(4)

array([0, 1, 2, 3])

In [32]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [35]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [42]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.concatenate((a, b))

c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim
array_example.size
array_example.shape

(3, 2, 4)

In [65]:
a = np.arange(6)
print(a)
b = a.reshape(3, 2)
print(b)


[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [69]:
a = np.arange(6)
a.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape
a2 = a[np.newaxis, :]
a2.shape
# 로우 벡터
row_vector = a[np.newaxis, :]
row_vector.shape
#컬럼 벡터
col_vector = a[:, np.newaxis]
col_vector.shape

(1, 6)

In [75]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [76]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [85]:
data = np.array([1, 2, 3])
data[1]
data[0:2]
data[1:]
data[-2:]


array([2, 3])

In [101]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])
five_up = (a >= 5)
print(five_up)
print(a[five_up])

divisible_by_2 = a[a%2==0]
print(divisible_by_2)

c = a[(a > 2) & (a < 11)]
print(c)

five_up = (a > 5) | (a == 5)
print(five_up)

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)
b

list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

print(a[b])

not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [107]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1

a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
np.vstack((a1, a2))

np.hstack((a1, a2))


array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [110]:
x = np.arange(1, 25).reshape(2, 12)

np.hsplit(x, 3)
np.hsplit(x, (3, 4))


[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [113]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0, :]
b1

b1[0] = 99
b1

a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [115]:
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [119]:
# 기본 배열 연산
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

data - ones

data * data

data / data


array([1., 1.])

In [123]:
a = np.array([1, 2, 3, 4])
a.sum()

b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)
b.sum(axis=1)



array([2, 4])

In [125]:
data = np.array([1.0, 2.0])
data * 1.6


array([1.6, 3.2])

In [128]:
data.max()
data.min()
data.sum()


np.float64(3.0)

In [133]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.sum()
a.min()
a.min(axis=0)


array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [140]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data
data[0, 1]
data[1:3]
data[0:2, 0]

data.max()
data.min()
data.sum()


np.int64(21)

In [141]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data
data.max(axis=0)
data.max(axis=1)


array([2, 5, 6])

In [142]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [143]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [145]:
np.ones((4, 3, 2))
np.ones(3)
np.zeros(3)
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3)


array([0.87288372, 0.80023667, 0.53149513])

In [146]:
np.ones((3, 2))
np.zeros((3, 2))
rng.random((3, 2))


array([[0.45865179, 0.31913096],
       [0.62516362, 0.21134244],
       [0.03178155, 0.23152006]])

In [147]:
rng.integers(5, size=(2, 4))


array([[0, 3, 4, 4],
       [1, 1, 3, 4]])

In [148]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)


[11 12 13 14 15 16 17 18 19 20]


In [149]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)


[ 0  2  3  4  5  6  7 12 13 14]


In [151]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])


[3 2 2 2 1 1 1 1 1 1]


In [152]:
unique_values = np.unique(a_2d)
print(unique_values)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [153]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [154]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


In [155]:
data.reshape(2, 3)
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [158]:
arr = np.arange(6).reshape((2, 3))
arr
arr.transpose()
arr.T


array([[0, 3],
       [1, 4],
       [2, 5]])

In [159]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)


Reversed Array:  [8 7 6 5 4 3 2 1]


In [162]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]
[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]
